// Generado a partir de los PDFs en /public/programas (Tomo II - Programas
// Separados, Plan 2026). Mapea el nombre de la materia mostrado en
// PlanDeEstudios.tsx al archivo PDF de su programa de estudios.
export const programFiles: Record<string, string> = {
  "Acústica y Óptica": "118 - Acústica y Óptica.pdf",
  "Amplificadores Electrónicos": "031 - Amplificadores Electrónicos.pdf",
  "Amplificadores para Microondas": "049 - Amplificadores para Microondas.pdf",
  "Análisis Numérico": "020 - Análisis Numérico.pdf",
  "Análisis de Circuitos Eléctricos": "019 - Análisis de Circuitos Eléctricos.pdf",
  "Aprovechamiento de Fuentes Renovables de Energía": "050 - Aprovechamiento de Fuentes Renovables de Energía.pdf",
  "Automatización": "037 - Automatización.pdf",
  "Bioelectrónica": "051 - Bioelectrónica.pdf",
  "Circuitos Integrados Analógicos": "038 - Circuitos Integrados Analógicos.pdf",
  "Circuitos y Sistemas Electrónicos para Comunicaciones": "043 - Circuitos y Sistemas Electrónicos para Comunicaciones.pdf",
  "Comunicación Multimodal": "013 - Comunicación Multimodal.pdf",
  "Control Industrial Programable de Gran Escala": "052 - Control Industrial Programable de Gran Escala.pdf",
  "Cultura de Paz y Resolución de Conflictos": "120 - Cultura de Paz y Resolución de Conflictos.pdf",
  "Cálculo Diferencial e Integral": "002 - Cálculo Diferencial e Integral.pdf",
  "Cálculo Vectorial": "008 - Cálculo Vectorial.pdf",
  "Dinámica de Sistemas Físicos": "021 - Dinámica de Sistemas Físicos.pdf",
  "Diseño Digital": "032 - Diseño Digital.pdf",
  "Dispositivos Electrónicos Programables": "053 - Dispositivos Electrónicos Programables.pdf",
  "Dispositivos y Circuitos Electrónicos": "025 - Dispositivos y Circuitos Electrónicos.pdf",
  "Ecuaciones Diferenciales": "009 - Ecuaciones Diferenciales.pdf",
  "Electricidad y Magnetismo": "014 - Electricidad y Magnetismo.pdf",
  "Electrónica de Potencia": "054 - Electrónica de Potencia.pdf",
  "Equipos Biomédicos Electrónicos Avanzados": "055 - Equipos Biomédicos Electrónicos Avanzados.pdf",
  "Finanzas en Ingeniería": "026 - Finanzas en Ingeniería.pdf",
  "Fuentes de Energía Eléctrica": "033 - Fuentes de Energía Eléctrica.pdf",
  "Fundamentos de Control": "027 - Fundamentos de Control.pdf",
  "Fundamentos para la Resolución de Problemas en Ingeniería": "003 - Fundamentos para la Resolución de Problemas en Ingeniería.pdf",
  "Física de Semiconductores": "022 - Física de Semiconductores.pdf",
  "Gestión Integral de Proyectos": "039 - Gestión Integral de Proyectos.pdf",
  "Gestión Óptima de la Generación": "056 - Gestión Óptima de la Generación.pdf",
  "Igualdad de Género en Ingeniería": "004 - Igualdad de Género en Ingeniería.pdf",
  "Ingeniería Económica": "034 - Ingeniería Económica.pdf",
  "Ingeniería de Datos e Inteligencia Artificial": "023 - Ingeniería de Datos e Inteligencia Artificial.pdf",
  "Ingeniería y Desarrollo Sostenible": "047 - Ingeniería y Desarrollo Sostenible.pdf",
  "Innovación, Emprendimiento y Negocios": "125 - Innovación, Emprendimiento y Negocios.pdf",
  "Instalaciones Eléctricas Industriales": "045 - Instalaciones Eléctricas Industriales.pdf",
  "Instrumentación Inteligente": "057 - Instrumentación Inteligente.pdf",
  "Introducción a los Circuitos de CD": "010 - Introducción a los Circuitos en CD.pdf",
  "Introducción a los Circuitos en CD": "010 - Introducción a los Circuitos en CD.pdf",
  "Introducción al Modelado de Fenómenos Físicos": "005 - Introducción al Modelado de Fenómenos Físicos.pdf",
  "Introducción al Modelado de Problemas en Fenómenos Físicos": "005 - Introducción al Modelado de Fenómenos Físicos.pdf",
  "Liderazgo Estratégico": "035 - Liderazgo Estratégico.pdf",
  "Matemáticas Avanzadas": "015 - Matemáticas Avanzadas.pdf",
  "Mecánica": "011 - Mecánica.pdf",
  "Medición e Instrumentación": "029 - Medición e Instrumentación.pdf",
  "Mems para Radiofrecuencia": "058 - Mems para Radiofrecuencia.pdf",
  "Microprocesadores y Microcontroladores": "040 - Microprocesadores y Microcontroladores.pdf",
  "Movilidad e Internacionalización I": "126 - Movilidad e Internacionalización I.pdf",
  "Movilidad e Internacionalización II": "127 - Movilidad e Internacionalización II.pdf",
  "Movilidad e Internacionalización III": "128 - Movilidad e Internacionalización III.pdf",
  "Movilidad e Internacionalización IV": "129 - Movilidad e Internacionalización IV.pdf",
  "Movilidad e Internacionalización IX": "134 - Movilidad e Internacionalización IX.pdf",
  "Movilidad e Internacionalización V": "130 - Movilidad e Internacionalización V.pdf",
  "Movilidad e Internacionalización VI": "131 - Movilidad e Internacionalización VI.pdf",
  "Movilidad e Internacionalización VII": "132 - Movilidad e Internacionalización VII.pdf",
  "Movilidad e Internacionalización VIII": "133 - Movilidad e Internacionalización VIII.pdf",
  "Movilidad e Internacionalización X": "135 - Movilidad e Internacionalización X.pdf",
  "Movilidad e Internacionalización XI": "136 - Movilidad e Internacionalización XI.pdf",
  "Máquinas Eléctricas": "028 - Máquinas Eléctricas.pdf",
  "Pensamiento Computacional": "006 - Pensamiento Computacional.pdf",
  "Planeación de la Expansión del Sistema Eléctrico": "059 - Planeación de la Expansión del Sistema Eléctrico.pdf",
  "Plantas Generadoras": "060 - Plantas Generadoras.pdf",
  "Probabilidad y Estadística": "016 - Probabilidad y Estadística.pdf",
  "Procesamiento Digital de Señales": "041 - Procesamiento Digital de Señales.pdf",
  "Protección de Redes Eléctricas": "061 - Protección de Redes Eléctricas.pdf",
  "Proyecto Integrador en Ingeniería": "048 - Proyecto Integrador en Ingeniería.pdf",
  "Química General": "017 - Química General.pdf",
  "Redes Eléctricas Resilientes": "046 - Redes Eléctricas Resilientes.pdf",
  "Redes Eléctricas de Distribución": "036 - Redes Eléctricas de Distribución.pdf",
  "Redes Eléctricas de Transmisión": "042 - Redes Eléctricas de Transmisión.pdf",
  "Robots Móviles": "062 - Robots Móviles.pdf",
  "Señales y Sistemas": "018 - Señales y Sistemas.pdf",
  "Sistemas Electrónicos": "063 - Sistemas Electrónicos.pdf",
  "Sistemas Electrónicos Embebidos": "064 - Sistemas Electrónicos Embebidos.pdf",
  "Sociedad, Cultura e Identidad": "012 - Sociedad, Cultura e Identidad.pdf",
  "Subestaciones Eléctricas": "065 - Subestaciones Eléctricas.pdf",
  "Temas Selectos de Bioingeniería I": "067 - Temas Selectos de Bioingeniería I.pdf",
  "Temas Selectos de Bioingeniería II": "068 - Temas Selectos de Bioingeniería II.pdf",
  "Temas Selectos de Bioingeniería III": "069 - Temas Selectos de Bioingeniería III.pdf",
  "Temas Selectos de Bioingeniería IV": "070 - Temas Selectos de Bioingeniería IV.pdf",
  "Temas Selectos de Bioingeniería V": "071 - Temas Selectos de Bioingeniería V.pdf",
  "Temas Selectos de Ciencias Sociales I": "121 - Temas Selectos de Ciencias Sociales I.pdf",
  "Temas Selectos de Ciencias Sociales II": "122 - Temas Selectos de Ciencias Sociales II.pdf",
  "Temas Selectos de Control I": "072 - Temas Selectos de Control I.pdf",
  "Temas Selectos de Control II": "073 - Temas Selectos de Control II.pdf",
  "Temas Selectos de Control III": "074 - Temas Selectos de Control III.pdf",
  "Temas Selectos de Control IV": "075 - Temas Selectos de Control IV.pdf",
  "Temas Selectos de Control V": "076 - Temas Selectos de Control V.pdf",
  "Temas Selectos de Electrónica Digital I": "088 - Temas Selectos de Electrónica Digital I.pdf",
  "Temas Selectos de Electrónica Digital II": "089 - Temas Selectos de Electrónica Digital II.pdf",
  "Temas Selectos de Electrónica Digital III": "090 - Temas Selectos de Electrónica Digital III.pdf",
  "Temas Selectos de Electrónica Digital IV": "091 - Temas Selectos de Electrónica Digital IV.pdf",
  "Temas Selectos de Electrónica Digital V": "092 - Temas Selectos de Electrónica Digital V.pdf",
  "Temas Selectos de Electrónica de Alta Frecuencia I": "083 - Temas Selectos de Electrónica de Alta Frecuencia I.pdf",
  "Temas Selectos de Electrónica de Alta Frecuencia II": "084 - Temas Selectos de Electrónica de Alta Frecuencia II.pdf",
  "Temas Selectos de Electrónica de Alta Frecuencia III": "085 - Temas Selectos de Electrónica de Alta Frecuencia III.pdf",
  "Temas Selectos de Electrónica de Alta Frecuencia IV": "086 - Temas Selectos de Electrónica de Alta Frecuencia IV.pdf",
  "Temas Selectos de Electrónica de Alta Frecuencia V": "087 - Temas Selectos de Electrónica de Alta Frecuencia V.pdf",
  "Temas Selectos de Eléctrica Electrónica I": "077 - Temas Selectos de Eléctrica Electrónica I.pdf",
  "Temas Selectos de Eléctrica Electrónica II": "078 - Temas Selectos de Eléctrica Electrónica II.pdf",
  "Temas Selectos de Eléctrica Electrónica III": "079 - Temas Selectos de Eléctrica Electrónica III.pdf",
  "Temas Selectos de Eléctrica Electrónica IV": "080 - Temas Selectos de Eléctrica Electrónica IV.pdf",
  "Temas Selectos de Eléctrica Electrónica V": "081 - Temas Selectos de Eléctrica Electrónica V.pdf",
  "Temas Selectos de Eléctrica Electrónica VI": "082 - Temas Selectos de Eléctrica Electrónica VI.pdf",
  "Temas Selectos de Humanidades I": "123 - Temas Selectos de Humanidades I.pdf",
  "Temas Selectos de Humanidades II": "124 - Temas Selectos de Humanidades II.pdf",
  "Temas Selectos de Producción y Utilización de la Energía I": "093 - Temas Selectos de Producción y Utilización de la Energía I.pdf",
  "Temas Selectos de Producción y Utilización de la Energía II": "094 - Temas Selectos de Producción y Utilización de la Energía II.pdf",
  "Temas Selectos de Producción y Utilización de la Energía III": "095 - Temas Selectos de Producción y Utilización de la Energía III.pdf",
  "Temas Selectos de Producción y Utilización de la Energía IV": "096 - Temas Selectos de Producción y Utilización de la Energía IV.pdf",
  "Temas Selectos de Producción y Utilización de la Energía V": "097 - Temas Selectos de Producción y Utilización de la Energía V.pdf",
  "Temas Selectos de Redes Eléctricas I": "098 - Temas Selectos de Redes Eléctricas I.pdf",
  "Temas Selectos de Redes Eléctricas II": "099 - Temas Selectos de Redes Eléctricas II.pdf",
  "Temas Selectos de Redes Eléctricas III": "100 - Temas Selectos de Redes Eléctricas III.pdf",
  "Temas Selectos de Redes Eléctricas IV": "101 - Temas Selectos de Redes Eléctricas IV.pdf",
  "Temas Selectos de Redes Eléctricas V": "102 - Temas Selectos de Redes Eléctricas V.pdf",
  "Temas Selectos de Señales y Sistemas Inteligentes I": "103 - Temas Selectos de Señales y Sistemas Inteligentes I.pdf",
  "Temas Selectos de Señales y Sistemas Inteligentes II": "104 - Temas Selectos de Señales y Sistemas Inteligentes II.pdf",
  "Temas Selectos de Señales y Sistemas Inteligentes III": "105 - Temas Selectos de Señales y Sistemas Inteligentes III.pdf",
  "Temas Selectos de Señales y Sistemas Inteligentes IV": "106 - Temas Selectos de Señales y Sistemas Inteligentes IV.pdf",
  "Temas Selectos de Señales y Sistemas Inteligentes V": "107 - Temas Selectos de Señales y Sistemas Inteligentes V.pdf",
  "Temas Selectos de Sistemas Electrónicos I": "108 - Temas Selectos de Sistemas Electrónicos I.pdf",
  "Temas Selectos de Sistemas Electrónicos II": "109 - Temas Selectos de Sistemas Electrónicos II.pdf",
  "Temas Selectos de Sistemas Electrónicos III": "110 - Temas Selectos de Sistemas Electrónicos III.pdf",
  "Temas Selectos de Sistemas Electrónicos IV": "111 - Temas Selectos de Sistemas Electrónicos IV.pdf",
  "Temas Selectos de Sistemas Electrónicos V": "112 - Temas Selectos de Sistemas Electrónicos V.pdf",
  "Temas Selectos de Sistemas Energéticos I": "113 - Temas Selectos de Sistemas Energéticos I.pdf",
  "Temas Selectos de Sistemas Energéticos II": "114 - Temas Selectos de Sistemas Energéticos II.pdf",
  "Temas Selectos de Sistemas Energéticos III": "115 - Temas Selectos de Sistemas Energéticos III.pdf",
  "Temas Selectos de Sistemas Energéticos IV": "116 - Temas Selectos de Sistemas Energéticos IV.pdf",
  "Temas Selectos de Sistemas Energéticos V": "117 - Temas Selectos de Sistemas Energéticos V.pdf",
  "Teoría Electromagnética": "024 - Teoría Electromagnética.pdf",
  "Termodinámica": "119 - Termodinámica.pdf",
  "Uso Eficiente de la Energía": "030 - Uso Eficiente de la Energía.pdf",
  "Visión Computacional": "066 - Visión Computacional.pdf",
  "Álgebra Lineal": "007 - Álgebra Lineal.pdf",
  "Álgebra y Geometría Analítica": "001 - Álgebra y Geometría Analítica.pdf",
  "Ética Profesional": "044 - Ética Profesional.pdf",
};

export function getProgramHref(name: string): string | null {
  const file = programFiles[name];
  return file ? `/programas/${encodeURIComponent(file)}` : null;
}
